import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:thread_clone/services/auth_service.dart';
import 'package:thread_clone/services/navigation_service.dart';
import 'package:thread_clone/services/threads_service.dart';
import 'package:thread_clone/utils/env.dart';
import 'package:thread_clone/utils/helper.dart';

class CreateThreadController extends GetxController {
  final AuthService authService = Get.find<AuthService>();

  // Reactive user data
  RxString name = ''.obs;
  RxnString userImageUrl = RxnString(null);

  // Thread content
  final TextEditingController controller = TextEditingController();
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();

  // Images attached to the thread
  final Rxn<File> image = Rxn<File>();

  // Loading state
  final RxBool isLoading = false.obs;

  final ThreadsService threadsService = Get.find<ThreadsService>();

  @override
  void onInit() {
    super.onInit();
    // Initialize reactive user info
    name.value = authService.user?.userMetadata?['name'] ?? '';
    userImageUrl.value = authService.user?.userMetadata?['image_url'] ?? '';
  }

  // ---------------- IMAGE MANAGEMENT ----------------
  void addImage() async {
    final source = await openImagePickerSheet();
    if (source != null) {
      final pickedImage = await pickImage(source);
      if (pickedImage != null) {
        image.value = File(pickedImage.path);
      }
    }
  }

  void removeImage() {
    if (image.value != null) {
      image.value = null;
    }
  }

  // ---------------- THREAD VALIDATION ----------------
  String? validateThread(String? value) {
    if (value == null || value.trim().isEmpty) {
      return "Thread content cannot be empty";
    }
    if (value.trim().length > 500) {
      return "Thread content cannot exceed 500 characters";
    }
    return null;
  }

  // ---------------- CREATE THREAD ----------------
  Future<void> createThread() async {
    if (isLoading.value) return;
    if (!formKey.currentState!.validate()) return;
    isLoading.value = true;
    try {
      String? uploadedImageUrl;
      // 🔹 Upload image if exists (single image as per table)
      if (image.value != null) {
        uploadedImageUrl = await threadsService.uploadThreadImage(file: image.value!, bucket: Env.s3Bucket);

      }
      // 🔹 Insert thread (id auto-generated by DB)
      await threadsService.createThread(
        content: controller.text.trim(),
        image:  uploadedImageUrl ,
        allowReplies: true,
      );

      // 🔹 Clear UI
      controller.clear();
      image.value = null;

      Get.find<NavigationService>().backToPrevIndex();
      showSnackBar("Success", "Thread posted successfully ✅");
    } on StorageException catch (e) {
      debugPrint("❌ Storage error: $e");
      showSnackBar("Error", "Failed to upload image ❌");
    } on AuthException catch (e) {
      debugPrint("❌ Auth error: $e");
      showSnackBar("Error", "Failed to post thread ❌");
    } catch (e, s) {
      debugPrint("❌ Error creating thread: $e");
      debugPrintStack(stackTrace: s);
      showSnackBar("Error", "Failed to post thread ❌");
    } finally {
      isLoading.value = false;
    }
  }
}
